export const GET_PLAYLISTS_REQUEST = 'GET_PLAYLISTS_REQUEST';
export const GET_PLAYLISTS_FAILURE = 'GET_PLAYLISTS_FAILURE';
export const GET_PLAYLISTS_SUCCESS = 'GET_PLAYLISTS_SUCCESS';

export const GET_FILTERS = 'GET_FILTERS';
export const SET_FILTERS = 'SET_FILTERS';
